mapped_names = {'0invader Cybersecurity': '0invader Cybersecurity',
 '1223': '1223',
 '1852': '1852',
 '2112 Industries': '2112 Industries',
 '3GIMBALS': '3GIMBALS',
 '4lifefitness': '4lifefitness',
 'ACC': 'ACC',
 'AID Upstate': 'AID Upstate',
 'AIT Austrian Institute of Technology': 'AIT Austrian Institute of Technology',
 'AKESOgen': 'AKESOgen',
 'ALIVE Wesleyan Church': 'ALIVE Wesleyan Church',
 'ALTEN': 'ALTEN',
 'ARA': 'ARA',
 'ASG': 'ASG',
 'AT&T': 'AT&T',
 'AT&T Ventures': 'AT&T',
 'ATI Physical Therapy': 'MX Physical Therapy',
 'Accenture': 'Accenture',
 'Accenture Technology': 'Accenture',
 'Accurate Background': 'Accurate Background',
 'Accusource Investigative Solutions, Inc.': 'Hodson P.I. - Investigative '
                                             'Solutions',
 'Acker Physical Therapy and Neurological Rehabilitation': 'Acker Physical '
                                                           'Therapy and '
                                                           'Neurological '
                                                           'Rehabilitation',
 'Action Global Communications': 'Action Global Communications',
 'Admiral Fluidics': 'Admiral Fluidics',
 'Adobe': 'Adobe',
 'Adsco Manufacturing LLC': 'Adsco Manufacturing LLC',
 'Advancing American Freedom': 'Advancing American Freedom',
 'Advoco, Part of Accenture': 'Accenture',
 'Afognak Native Corporation': 'Afognak Native Corporation',
 'AgFirst Farm Credit Bank': 'AgFirst Farm Credit Bank',
 'Air2Web': 'Air2Web',
 'Aldridge Pite, LLP': 'Aldridge Pite, LLP',
 'Alescent': 'Alescent',
 'Alex Reynolds for County Council': 'Alex Reynolds for County Council',
 'Alexandra Public Relations': 'Alexandra Public Relations',
 'Alexion Pharmaceuticals, Inc.': 'Alexion Pharmaceuticals, Inc.',
 'Allstate': 'Allstate',
 'Ally': 'Ally',
 'Altium Packaging': 'Altium Packaging',
 'Altius Technologies': 'Altius Technologies',
 'Amazon': 'Amazon',
 'Amazon Web Services': 'Amazon',
 'America Reads at Clemson University': 'America Reads at Clemson University',
 'American Stage Festival': 'American Stage Festival',
 'American Tire Distributors': 'American Tire Distributors',
 'American University in Bulgaria': 'American University in Bulgaria',
 'An Orthodox Workshop': 'An Orthodox Workshop',
 'AnMed': 'AnMed',
 'Anderson Area YMCA ': 'Ymca - Deland',
 'Anderson High School': 'Daniel High School',
 'Anderson Regional Joint Water System': 'Anderson Regional Joint Water System',
 'Anderson University (SC)': 'Kansai University',
 'Anderson-Negele': 'Anderson-Negele',
 'Angeles University Foundation': 'National Science Foundation ',
 'AnyDay Rent': 'AnyDay Rent',
 'Apex Private & Fire Investigative Services': 'Apex Private & Fire '
                                               'Investigative Services',
 'AppFolio': 'AppFolio',
 'Apple': 'Apple',
 'Applied Research Consultants ': 'Applied research Center (ARC)',
 'Applied research Center (ARC)': 'Applied research Center (ARC)',
 'Aptech': 'Aptech',
 'Aramark': 'ARA',
 'Arcadia University': 'Primrose Schools',
 'Archana Info & Mgmt. Services': 'Archana Info & Mgmt. Services',
 'Arsenic': 'Arsenic',
 'Arthur M. Spiro Institute for Entrepreneurial Leadership': 'Arthur M. Spiro '
                                                             'Institute for '
                                                             'Entrepreneurial '
                                                             'Leadership',
 'Arup': 'Arup',
 'Ascendancy': 'Ascendancy',
 'Ascendancy Strategic Partners': 'Business Strong Alliance',
 'Ashley Ridge High School': 'Daniel High School',
 'Asr Enterprises LLC': 'Capabilities LLC',
 'Associates Insectary': 'Associates Insectary',
 'Atlantis': 'Atlantis',
 'Atlas Autism Health': 'Atlas Autism Health',
 'Attune ': 'AT&T',
 'Auburn University': 'NCAA',
 'Austin Macauley Publishers': 'Austin Macauley Publishers',
 'Avalon College Advising': 'Avalon College Advising',
 'Avolta': 'Avolta',
 'B. Riley FBR, Inc.': 'B. Riley FBR, Inc.',
 'BAE Systems Applied Intelligence': 'BAE Systems Applied Intelligence',
 'BCF': 'BCF',
 'BIOTRONIK': 'BIOTRONIK',
 'BMW Group Plants': 'BMW Group Plants',
 'BMW Manufacturing Co., LLC': 'BMW Manufacturing Co., LLC',
 'BNY': 'BNY',
 'Back River Paddle Co.': 'Back River Paddle Co.',
 'Bandit Lites, Inc.': 'Bandit Lites, Inc.',
 'Battelle': 'Battelle',
 'Batteries Plus': 'Batteries Plus',
 'Baukunst': 'Baukunst',
 'Baylor University': 'NCAA',
 'Bdelo ltd': 'Bdelo ltd',
 'BeCrowned': 'BeCrowned',
 'Beaufort County Schools': 'Beaufort County Schools',
 'Beaufort Memorial Hospital': 'Beaufort County Schools',
 'Becker & Company': 'Becker & Company',
 'Beeby, Inc.': 'Beeby, Inc.',
 'BehaviorEra Ventures LLC': 'VentureSouth',
 'Belk': 'Belk',
 'Bellhop': 'Bellhop',
 "Ben & Jerry's": "Ben & Jerry's",
 'Benore Logistic Systems, Inc.': 'Benore Logistic Systems, Inc.',
 'Bexar County CSCD': 'Bexar County CSCD',
 'Bexar County Pretrial Services': 'Bexar County CSCD',
 'BigBear.ai': 'BigBear.ai',
 'Biselex Kenya': 'Biselex Kenya',
 'Blackbaud': 'Blackbaud',
 'Blast Analytics': 'Blast Analytics',
 'Blend, Inc.': 'Blend, Inc.',
 'Bloodhound Investigations, LLC.': 'Bloodhound Investigations, LLC.',
 'Blount Memorial Hospital': 'Blount Memorial Hospital',
 'Blue Hill Coffee & Tea CO.': 'Joe Coffee Company',
 'Blue Mantis': 'Blue Mantis',
 'Blue Raven Solar': 'Blue Raven Solar',
 'Board of Elections - City of New York': 'Board of Elections - City of New '
                                          'York',
 'Bon Secours Health System Ireland': 'Bon Secours Health System Ireland',
 'Bon Secours Mercy Health': 'Triune Mercy Center',
 'Bon Secours Wellness Arena': 'Bon Secours Wellness Arena',
 'Boomering Inc': 'Boomering Inc',
 'Booz Allen Hamilton': 'Booz Allen Hamilton',
 'Borden Ladner Gervais LLP ': 'Borden Ladner Gervais LLP ',
 'Bosch Rexroth': 'Bosch Rexroth',
 'Bostwick Laboratories': 'Bostwick Laboratories',
 'Bounteous': 'Bounteous',
 'Boys & Girls Club of Marion County': 'Boys & Girls Club of Marion County',
 'Brandcatz': 'Brandcatz',
 'Breakthrough Radio': 'RadioShack',
 'Breakthru Beverage Group': 'Breakthru Beverage Group',
 'Brickyard': 'Brickyard',
 'Brookfield Business Partners': 'Brookfield Business Partners',
 'Brooks Center For the Performing Arts': 'Brooks Center For the Performing '
                                          'Arts',
 'Brown Brothers Harriman': 'Brown Brothers Harriman',
 'Buffalo Animal Adventures, Inc.': 'Buffalo Animal Adventures, Inc.',
 'Business Strong Alliance': 'Business Strong Alliance',
 'Byu Rugby': 'Byu Rugby',
 'C2 Education': 'C2 Education',
 'CAFCA': 'CAFCA',
 'CBDfx': 'BCF',
 'CGI': 'CGI',
 'CLEMSON DOWNS RETIREMENT COMMUNITY INC': 'ClemsonLIFE',
 'CONFIDENTIAL Legaltech Company': 'CONFIDENTIAL Legaltech Company',
 'COPS': 'COPS',
 'CUhackit': 'CUhackit',
 'CVS Health': 'CVS Health',
 'Caffe Ladro - Ladro Roasting': 'Caffe Ladro - Ladro Roasting',
 'Call Federal Credit Union': 'Call Federal Credit Union',
 'Callisto Media': 'Callisto Media',
 'Cambridge Review of International Affairs': 'Cambridge Review of '
                                              'International Affairs',
 'Camp Ozark': 'Camp Ozark',
 'Camps Kahdalea and Chosatonga': 'WinShape Camps',
 'Capabilities LLC': 'Capabilities LLC',
 'Capgemini': 'Capsoft',
 'Capgemini Salesforce': 'Capgemini Salesforce',
 'Capital One': 'Capsoft',
 'Capsoft': 'Capsoft',
 'Capstone Green Energy': 'Capstone Green Energy',
 'CarbonCents': 'CarbonCents',
 'CarbonLogicX, Inc.': 'StoneX Group Inc.',
 'Cardinal Group Companies': 'ClubCorp Holdings',
 'CareerBuilder Employment Screening': 'CareerBuilder Employment Screening',
 'Carolina Girls': 'Carolina Girls',
 'Carolina Legal Staffing': 'Carolina Legal Staffing',
 'Carolina Precision Foods, LLC': 'Carolina Precision Foods, LLC',
 'Carters Distribution Center': 'Carters Inc.',
 'Carters Inc.': 'Carters Inc.',
 'Casa Mañana Theatre': 'Casa Mañana Theatre',
 'Case Western Reserve University': 'US Army Reserve',
 'Cataphora': 'Cataphora',
 'Celanese': 'Celanese',
 'Celon Laboratories': 'Celon Laboratories',
 'Center for Analytics (Institute for the Study of Violent Groups)': 'Center '
                                                                     'for '
                                                                     'Analytics '
                                                                     '(Institute '
                                                                     'for the '
                                                                     'Study of '
                                                                     'Violent '
                                                                     'Groups)',
 'Center for Career and Professional Development-Clemson University': 'ClemsonLIFE',
 'Center for Intelligence Research Analysis and Training (CIRAT)': 'Center for '
                                                                   'Intelligence '
                                                                   'Research '
                                                                   'Analysis '
                                                                   'and '
                                                                   'Training '
                                                                   '(CIRAT)',
 'Center for an Informed Public': 'Center for an Informed Public',
 'Centrifuge Systems, Inc': 'Centrifuge Systems, Inc',
 'Charged Studios': 'Charged Studios',
 'Charleston ENT & Allergy': 'Charleston ENT & Allergy',
 'Charleston Vacation Services': 'Charleston Vacation Services',
 'Chasen Music': 'Chasen Music',
 'Cheeky Labs': 'Cheeky Labs',
 'Chi Omega Fraternity- Psi Kappa Chapter': 'Delta Delta Delta Sorority',
 'Chicago Inno': 'Chicago Inno',
 'Chick-fil-A Corporate Support Center': 'Chick-fil-A Corporate Support Center',
 'Chick-fil-A Restaurants': 'Chicken Salad Chick',
 'Chicken Salad Chick': 'Chicken Salad Chick',
 "Children's Museum of the Lowcountry": "Children's Museum of the Lowcountry",
 'Christ Church Episcopal': 'Grace Church ',
 'Circinus, LLC': 'Citigold',
 'Cisive': 'cis',
 'Citigold': 'Citigold',
 'Citizens for Jake Zimmerman': 'Day & Zimmermann',
 'City of Gaithersburg': 'City of Gaithersburg',
 'City of Greenville, South Carolina': 'Greenville Water',
 'City of Jacksonville NC ': 'City of Jacksonville NC ',
 'Clemson Academic Success Center': 'Clemson VIPR-GS Research Center',
 'Clemson Alumni Association': 'ClemsonLIFE',
 'Clemson Build': 'ClemsonLIFE',
 'Clemson Elementary School': 'ClemsonLIFE',
 'Clemson Engineers for Developing Communities': 'Clemson VIPR-GS Research '
                                                 'Center',
 'Clemson Rural Health': 'ClemsonLIFE',
 'Clemson University': 'ClemsonLIFE',
 'Clemson University - College of Agriculture, Forestry & Life Sciences': 'Clemson '
                                                                          'University '
                                                                          '- '
                                                                          'College '
                                                                          'of '
                                                                          'Agriculture, '
                                                                          'Forestry '
                                                                          '& '
                                                                          'Life '
                                                                          'Sciences',
 'Clemson University Athletic Department': 'ClemsonLIFE',
 'Clemson University Center for Student Leadership & Engagement': 'Clemson '
                                                                  'University '
                                                                  'Social '
                                                                  'Media '
                                                                  'Listening '
                                                                  'Center',
 'Clemson University Center for Workforce Development ': 'Clemson VIPR-GS '
                                                         'Research Center',
 'Clemson University College of Behavioral, Social and Health Sciences': 'Clemson '
                                                                         'University '
                                                                         'College '
                                                                         'of '
                                                                         'Behavioral, '
                                                                         'Social '
                                                                         'and '
                                                                         'Health '
                                                                         'Sciences',
 'Clemson University College of Engineering, Computing and Applied Sciences': 'Clemson '
                                                                              'VIPR-GS '
                                                                              'Research '
                                                                              'Center',
 'Clemson University College of Science': 'ClemsonLIFE',
 'Clemson University Department of Bioengineering': 'Clemson VIPR-GS Research '
                                                    'Center',
 'Clemson University Graduate School': 'ClemsonLIFE',
 'Clemson University Honors College': 'ClemsonLIFE',
 'Clemson University Research Foundation': 'Clemson VIPR-GS Research Center',
 'Clemson University Science Outreach Center': 'Clemson VIPR-GS Research '
                                               'Center',
 'Clemson University Social Media Listening Center': 'Clemson University '
                                                     'Social Media Listening '
                                                     'Center',
 'Clemson University Summer Scholars': 'ClemsonLIFE',
 'Clemson VIPR-GS Research Center': 'Clemson VIPR-GS Research Center',
 'Clemson Wesley': 'ClemsonLIFE',
 'ClemsonLIFE': 'ClemsonLIFE',
 'Clerk': 'Clerk',
 'Clinisys': 'Clinisys',
 'Cloud Court, Inc.': 'Cloud Court, Inc.',
 'ClubCorp Holdings': 'ClubCorp Holdings',
 'Clyde': 'Clyde',
 'CoNexionHR': 'CoNexionHR',
 'CodaKid': 'CodaKid',
 'Code Ninjas': 'Code Ninjas',
 'CodePath': 'CodePath',
 'Codexio': 'Codexio',
 'Coherent Corp.': 'Blend, Inc.',
 'Coherent Inc.': 'Blend, Inc.',
 'Columbia Engineering': 'Columbia Hospitality',
 'Columbia Hospitality': 'Columbia Hospitality',
 'Columbia University': 'UMBC',
 'Columbia University Press': 'Columbia University Press',
 'Command Investigations': 'Command Investigations',
 'Committe for Public Counsel Services': 'Committe for Public Counsel Services',
 'Community Medical Services': 'Medical Solutions',
 'Conagra Brands': 'Conagra Brands',
 'Connecticut Bureau of Criminal Investigation': 'Connecticut Bureau of '
                                                 'Criminal Investigation',
 'Continental Corporation': 'ClubCorp Holdings',
 'Convene Strategies': 'Convene Strategies',
 'Cook County Treasurer': 'Cook County Treasurer',
 'Cornell Tech': 'Cornell Tech',
 'Cornell University': 'Cornell Tech',
 'Cornerstone Autism Center': 'Cornerstone Autism Center',
 'Cornerstone Investigative Services, Inc': 'Cornerstone Investigative '
                                            'Services, Inc',
 'Corning Incorporated': 'Corning Incorporated',
 'Corporate Resolutions Inc.': 'Corporate Resolutions Inc.',
 'CountryWide Debt Relief': 'CountryWide Debt Relief',
 'CoventBridge Group': 'Oxenham Group',
 'Covet': 'Covet',
 'Craft Axe Throwing': 'Craft Axe Throwing',
 'Crawford': 'Crawford',
 'Creative Inquiry + Undergraduate Research': 'Creative Inquiry + '
                                              'Undergraduate Research',
 'Credo Software': 'Credo Software',
 'CriticalRiver Inc.': 'CriticalRiver Inc.',
 'Cromer Food Services': 'Cromer Food Services',
 'Crowley': 'Crowley',
 'Cru': 'Cru',
 'Cruise Line Agency of Alaska': 'Cruise Line Agency of Alaska',
 'Crystal Equation Corporation': 'Crystal Equation Corporation',
 'Crystal View Aerial': 'Crystal View Aerial',
 'Cuisine Unlimited': 'Unlimited',
 'Custom tees and clothing': 'Custom tees and clothing',
 'DE RISC GROUP': 'DE RISC GROUP',
 'DEVRIES GLOBAL': 'DEVRIES GLOBAL',
 "DICK'S Sporting Goods": "DICK'S Sporting Goods",
 'DSW Designer Shoe Warehouse': 'DSW Designer Shoe Warehouse',
 'DTU - Technical University of Denmark': 'Kansai University',
 'DW Daniel High School': 'Daniel High School',
 'DW-C Learning': 'DW-C Learning',
 'Danfoss': 'Danfoss',
 'Danfoss Fluid Power': 'Danfoss',
 'Daniel High School': 'Daniel High School',
 'Danish Refugee Council': 'Danish Refugee Council',
 'Dar-e-Arqam Schools': 'Dar-e-Arqam Schools',
 'DataLab USA': 'DataLab USA',
 'DataOpus': 'DataOpus',
 'Dawn Golden': 'Dawn Golden',
 'Day & Zimmermann': 'Day & Zimmermann',
 'Deal Armstrong': 'Deal Armstrong',
 'Deloitte': 'Deloitte',
 'Delta Delta Delta Sorority': 'Delta Delta Delta Sorority',
 'Department of Family and Children Services': 'National Child Protection Task '
                                               'Force ',
 'Design Trust for Public Space': 'Design Trust for Public Space',
 'Design for America': 'Design for America',
 'Deskpass': 'Deskpass',
 'Diamond Investigations': 'Diamond Investigations',
 'Diginius': 'Diginius',
 'Digistream Inc.': 'Diginius',
 'Disney Experiences': 'Disneyland Resort',
 'Disneyland Resort': 'Disneyland Resort',
 'Disrupting Global Cybercrime & Human Exploitation': 'Disrupting Global '
                                                      'Cybercrime & Human '
                                                      'Exploitation',
 'Distinguished Young Women': 'Distinguished Young Women',
 'DivaDance': 'DivaDance',
 'DomainTools': 'DomainTools',
 "Domino's": "Domino's",
 'DoorDash': 'DoorDash',
 'Dorchester School District 2': 'Dorchester School District 2',
 'Downtown Dayton Partnership': 'Downtown Dayton Partnership',
 'Drobots Company': 'Drobots Company',
 'Dunami Inc.': 'Dunami Inc.',
 "Dunkin'\u200b": "Dunkin'\u200b",
 'Dunlap and Associates, Inc.': 'Dunami Inc.',
 'EO Charging': 'EO Charging',
 'EP+Co': 'EP+Co',
 'EPIC iO Technologies': 'EPIC iO Technologies',
 'EXCEL REHAB & SPORTS': 'EXCEL REHAB & SPORTS',
 'EXO Checkout': 'EXO Checkout',
 'East Carolina University': 'Kenyon College',
 'Eastern TV (Love & Hip-Hop Hollywood Season 3)': 'Eastern TV (Love & Hip-Hop '
                                                   'Hollywood Season 3)',
 'Eastman Chemical Company-Tire Additives business': 'American Tire '
                                                     'Distributors',
 'Edge Fitness': 'Edge Fitness',
 'Education Solutions Services': 'Education Solutions Services',
 'Electrical Engineering and Computer Science': 'Electrical Engineering and '
                                                'Computer Science',
 'Element AI, a ServiceNow company': 'Element AI, a ServiceNow company',
 'Eleos Technologies': 'Eleos Technologies',
 'Elevation Capital Group, LLC': 'Capabilities LLC',
 'Elkmont Trading Company': 'Elkmont Trading Company',
 'Embassy of the United States of America, London': 'Embassy of the United '
                                                    'States of America, London',
 'Endeavor Communities': 'Endeavor Communities',
 'Ender': 'Ender',
 'EngiNearU Online Tutoring Agency': 'Tutor.com',
 'Equinox': 'Equinox',
 'EstateGrid.co': 'EstateGrid.co',
 'Eternity Foundation': 'Eternity Foundation',
 'Ethos': 'Ethos',
 'Eurasia Center': 'Eurasia Center',
 'Euromonitor International': 'Euromonitor International',
 'Everest': 'Everest',
 'FS Claim Solutions: A Verisk Business': 'FS Claim Solutions: A Verisk '
                                          'Business',
 'Facticon Investigations, Inc.': 'Facticon Investigations, Inc.',
 'Falls Fintech': 'Falls Fintech',
 'Famous Birthdays': 'Famous Birthdays',
 'Faneuil Inc': 'Faneuil Inc',
 'Farsight Security, Inc.': 'Farsight Security, Inc.',
 'FastFetch': 'FastFetch',
 'Federal Public Defender, Middle District of Tennessee': 'Federal Public '
                                                          'Defender, Middle '
                                                          'District of '
                                                          'Tennessee',
 'Federal Reserve Board': 'US Army Reserve',
 'Fiesta Mexican Restaurant': 'Fiesta Mexican Restaurant',
 'First Aid Pro - RTO 40407': 'First Aid Pro - RTO 40407',
 'First Quality': 'First Quality',
 'First Tuesday Strategies': 'First Tuesday Strategies',
 'FiscalNote': 'FiscalNote',
 'Fiserv Korea': 'Fiserv Korea',
 'Florida Atlantic University': 'NCAA',
 'Florida Atlantic University - College of Business': 'Medical University of '
                                                      'South Carolina',
 'Florida State University': 'NCAA',
 'Fluor Corporation': 'Fluor Corporation',
 'Foothills Area YMCA': 'Ymca - Deland',
 'Fortune Cookies Chinese Bistro': 'Fortune Cookies Chinese Bistro',
 'Forward Fund Chicago': 'Forward Fund Chicago',
 'Foundation for Law & International Affairs ': 'Cambridge Review of '
                                                'International Affairs',
 'Franciscan University of Steubenville': 'Lafayette College',
 "Franklin's Printing": "Franklin's Printing",
 'Frasco': 'Sysco',
 'Freeway Church': 'Grace Church ',
 'Friends with Benefits': 'Friends with Benefits',
 'Full moon films': 'Full moon films',
 'Fund for the City of New York': 'Forward Fund Chicago',
 'Furman University': 'Kansai University',
 'GCI Health': 'GCI Health',
 'GE Vernova': 'GE Vernova',
 'Gailey Eye Clinic': 'Gailey Eye Clinic',
 'Galesburg Cottage Hospital': 'Blount Memorial Hospital',
 'Galesburg Terrace Nursing Ctr': 'Galesburg Terrace Nursing Ctr',
 'Gaming Outfitters': 'Gaming Outfitters',
 'Gardele': 'Gardele',
 'Gates/Arrow Distributing Inc.': 'Gates/Arrow Distributing Inc.',
 'Genus AI': 'Genus AI',
 'Georgia Pacific': 'Georgia Pacific',
 'Georgia Tech Athletic Association': 'Teach and Learn with Georgia',
 'Gerson Lehrman Group': 'Gerson Lehrman Group',
 'Giant Oak, Inc.': 'Giant Oak, Inc.',
 'Gibson Dunn': 'Gibson Dunn',
 'Glenmoor Continuing Care Retirement Community': 'Glenmoor Continuing Care '
                                                  'Retirement Community',
 'Glide Animation, LLC': 'Glide Animation, LLC',
 'Global Crossing': 'Global Crossing',
 'Gnorth and Son': 'Gnorth and Son',
 'GoHealth Urgent Care': 'GoHealth Urgent Care',
 'Golden Concierge Insurance': 'Golden Concierge Insurance',
 'Google': 'Webs',
 'Google Workspace': 'Google Workspace',
 'Goonj': 'Goonj',
 'Gotcha Sportfishing': 'Gotcha Sportfishing',
 'Grace Church ': 'Grace Church ',
 'Grace City Church': 'Grace Church ',
 'Grant Tax': 'Grant Tax',
 'Greenlight Capital': 'Greenlight Capital',
 'Greenville Area Development Corporation ': 'Greenville County Public '
                                             'Defender',
 'Greenville County Public Defender': 'Greenville County Public Defender',
 'Greenville Local Development Corporation': 'Greenville County Public '
                                             'Defender',
 'Greenville Mental Health Ctr': 'Greenville Mental Health Ctr',
 'Greenville Technical College': 'Tri-County Technical College',
 'Greenville Water': 'Greenville Water',
 'Greenwood Genetic Center': 'Greenwood Genetic Center',
 'Grizz Logistics': 'Grizz Logistics',
 'Grosse Pointe Woods Public Safety': 'Grosse Pointe Woods Public Safety',
 'Groupe Michelin': 'Michelin',
 'GrowExx': 'GrowExx',
 'GrowthMentor': 'GrowthMentor',
 'Guitar Artistry Program': 'Guitar Artistry Program',
 'HP': 'HP',
 'HRH Consulting LLC': 'HRSDC',
 'HRSDC': 'HRSDC',
 'Habitat for Humanity of Greenville County': 'Greenville County Public '
                                              'Defender',
 'Haggar Clothing Co.': 'Haggar Clothing Co.',
 'Hallmark Cards': 'Hallmark Cards',
 'Hamlin Creative': 'Hamlin Creative',
 'Harborview Medical Center': 'Lexington Medical Center',
 'Harri': 'Harri',
 'Havas Formula': 'Havas Formula',
 'Have More Fun': 'Have More Fun',
 'Hayden AI': 'Hayden AI',
 'HeadOn': 'HeadOn',
 'Healthstep: Benefits-as-a-Service for Small Business and Startups & Benefits-for-brewers': 'Healthstep: '
                                                                                             'Benefits-as-a-Service '
                                                                                             'for '
                                                                                             'Small '
                                                                                             'Business '
                                                                                             'and '
                                                                                             'Startups '
                                                                                             '& '
                                                                                             'Benefits-for-brewers',
 'HelloWallet': 'HelloWallet',
 'Henderson Marketing': 'Henderson Marketing',
 'Hertog Foundation': 'Hertog Foundation',
 'Hexagon Asset Lifecycle Intelligence': 'Hexagon Asset Lifecycle Intelligence',
 'Hey Rowan': 'Hey Rowan',
 'HiCounselor': 'HiCounselor',
 'High School Heisman': 'NCAA',
 'High Side Technology': 'High Side Technology',
 'Higher Education Innovation Inc.': 'University Innovation Fellows',
 'Hinge Social': 'Hinge Social',
 'Hodson P.I. - Investigative Solutions': 'Hodson P.I. - Investigative '
                                          'Solutions',
 'Hogan Assessment Systems': 'Hogan Assessment Systems',
 'Homewatch CareGivers': 'Homewatch CareGivers',
 'Honk': 'Honk',
 'Horizons Student Enrichment': 'Horizons Student Enrichment',
 'Horry-Georgetown Technical College': 'Kenyon College',
 'Houses': 'Houses',
 'Hr Risk Mitigation/Lex Pro Research': 'Hr Risk Mitigation/Lex Pro Research',
 'Hubbell Incorporated': 'Hubbell Incorporated',
 'Human AI Empowerment Lab, Clemson University': 'Human-AI Empowerment Lab',
 'Human-AI Empowerment Lab': 'Human-AI Empowerment Lab',
 'Hustle Fund': 'Hustle Fund',
 'Hyde Park Capital': 'Hyde Park Capital',
 'IBM Security Services': 'IBM Security Services',
 'ICode Austin': 'ICode Austin',
 'IFA- North America LLC': 'IFA- North America LLC',
 'IKON Office Solutions': 'IKON Office Solutions',
 'IMG PT': 'IMG PT',
 'IPQualityScore - IPQS.com': 'IPQualityScore - IPQS.com',
 'ITG': 'ASG',
 'ITS Planners and Engineers Ltd': 'Land Planning Associates Inc',
 'Icreon': 'Icreon',
 'Illumina': 'Illumina',
 'Impact Upgrade': 'Impact Upgrade',
 'Infinity': 'Infinity',
 'Infinity Constellation': 'Infinity',
 'Ingersoll Rand': 'Ingersoll Rand',
 'Ingles Markets': 'Ingles Markets',
 'Ingraham Property Management': 'Ingraham Property Management',
 'Innovate Anderson': 'Anderson-Negele',
 'Institute for Higher Education Policy': 'Progressive Policy Institute',
 'Institute for Policy Research': 'Progressive Policy Institute',
 "Int'l Claim Association (ICA)": 'New England Claim Association',
 'Integrated Support Systems ': 'Integrated Support Systems ',
 'Intensity Analytics': 'Intensity Analytics',
 'Intermountain Health': 'MUSC Health',
 'International Atomic Energy Agency ': 'International Atomic Energy Agency ',
 'Intrasphere Technologies': 'Intrasphere Technologies',
 'Invisible Technologies': 'Invisible Technologies',
 'Island Rides Sc': 'Island Rides Sc',
 'Isle of Palms Beach Chair Co': 'Isle of Palms Beach Chair Co',
 'Itron, Inc.': 'Itron, Inc.',
 'J-Teen Leadership': 'J-Teen Leadership',
 'J3 Growth Advisory': 'J3 Growth Advisory',
 'JPMorganChase': 'JPMorganChase',
 'JVS Media': 'JVS Media',
 'Jack Porter, Inc.': 'Jack Porter, Inc.',
 'Jackson Hole Classical Academy': 'Jackson Hole Classical Academy',
 'Jeff Dezen Public Relations': 'Jeff Dezen Public Relations',
 'Jefferson High School': 'Daniel High School',
 'Jefferson Middle School Volleyball': 'Volley One Volleyball Club',
 'Jenson8': 'Jenson8',
 'Jeppesen Sanderson': 'Jeppesen Sanderson',
 'Jitters Brewing Company': 'Jitters Brewing Company',
 'Joe Coffee Company': 'Joe Coffee Company',
 'John Jay College (CUNY)': 'Kenyon College',
 'John Leslie Consulting': 'John Leslie Consulting',
 'Johns Hopkins Applied Physics Laboratory': 'Johns Hopkins Applied Physics '
                                             'Laboratory',
 'Johnson Controls': 'Johnson Controls',
 'Journal Communications': 'Journal Communications',
 'Juniper Greenville': 'Greenville Water',
 'KATSH DIGITAL ID': 'KATSH DIGITAL ID',
 'KCI': 'KCI',
 'KCSA Strategic Communications': 'KCI',
 'KNACK.': 'KNACK.',
 'KOREAN SCHOOL OF COLUMBIA': 'Korean School of Guam',
 'KPMG US': 'KPMG US',
 'Kajiado Forum for Community Development (KFCD)': 'Kajiado Forum for '
                                                   'Community Development '
                                                   '(KFCD)',
 'Kanenson PI LLC': 'Kanenson PI LLC',
 'Kansai University': 'Kansai University',
 'Kenyon College': 'Kenyon College',
 'Kilpatrick Townsend & Stockton': 'Kilpatrick Townsend & Stockton',
 'Kinguin': 'Kinguin',
 "Kohl's": "Lowe's",
 'Korean School of Guam': 'Korean School of Guam',
 'Kroger': 'Kroger',
 'Kroll': 'Kroll',
 'Kumon North America': 'Kumon North America',
 'Kustom Krust': 'Kyrus',
 'Kyrus': 'Kyrus',
 'LG India': 'LG India',
 'LPL Financial': 'LPL Financial',
 'Lab.rynth': 'Lab.rynth',
 'LabAnswer': 'Lab.rynth',
 'Lafayette College': 'Lafayette College',
 'Lake Murray Boat Club': 'Back River Paddle Co.',
 'Lakonic Studio': 'Lakonic Studio',
 'Land Planning Associates Inc': 'Land Planning Associates Inc',
 'Land of Sky Regional Council': 'Land of Sky Regional Council',
 'Lanier Treatment Center': 'Lanier Treatment Center',
 'Launch Innovative Business Accelerator': 'Launch Innovative Business '
                                           'Accelerator',
 'Law Office Of Seana B. Thomas, APC': 'Law Office Of Seana B. Thomas, APC',
 'Law Offices of James F. Walker': 'Law Offices of James F. Walker',
 'LeanTK': 'Belk',
 'Leap Gaming': 'Leap Gaming',
 'Lee & Associates Greenville / Spartanburg': 'Lee & Associates Greenville / '
                                              'Spartanburg',
 'Legal Benchmarking Group': 'Legal Benchmarking Group',
 'Leitner Homes LLC': 'Leitner Homes LLC',
 'Les Mills ': 'Les Mills ',
 'Let People See': 'Let People See',
 'Lewis Abode': 'Lewis Abode',
 'LexPro Research LLC': 'LexPro Research LLC',
 'Lexington Medical Center': 'Lexington Medical Center',
 'Life Lift': 'Lifesaver',
 'Life on the Bay': 'Life on the Bay',
 'LifePoint Church of Oconee': 'Grace Church ',
 'Lifesaver': 'Lifesaver',
 'Lincoln Memorial University': 'Kenyon College',
 'Link Digital': 'Link Digital',
 'LinkedIn': 'LinkedIn',
 'Little Caesars Pizza': 'Little Caesars Pizza',
 'Live Oaks Restaurant': 'Giant Oak, Inc.',
 'Loaves & Fishes Greenville': 'Greenville Water',
 'Loggerhead Marinelife Center': 'Loggerhead Marinelife Center',
 "Lowe's": "Lowe's",
 'Lowers Risk Group': 'Lowers Risk Group',
 'Lucid Software': 'Lucid Software',
 'Lynda.com': 'Lynda.com',
 'MARSHALLS LLC': 'MARSHALLS LLC',
 'MBD Partners': 'MBD Partners',
 'MIA Consulting LLC': 'MIA Consulting LLC',
 'MITRE': 'MITRE',
 'MLQ ATTORNEY SERVICES': 'MLQ ATTORNEY SERVICES',
 'MST ': 'MST ',
 'MTN Group': 'MTN Group',
 'MUSC Health': 'MUSC Health',
 'MX Physical Therapy': 'MX Physical Therapy',
 'Mad Dogg Athletics®': 'Mad Dogg Athletics®',
 'Main Street Banks': 'Main Street Banks',
 'Maltego Technologies': 'Maltego Technologies',
 'Manhattan Associates': 'Manhattan Associates',
 "Manhattan District Attorney's Office": 'Manhattan Associates',
 'Marion Kanenson': 'Kanenson PI LLC',
 'Market Basket': 'Market Basket',
 'Marriner Construction': 'Marriner Construction',
 "Marsh's Edge": "Marsh's Edge",
 'Marshall Investigative Group': 'MARSHALLS LLC',
 'Martin Marietta': 'Martin Marietta',
 'Mass State Police- Forensic Crime Lab': 'Mass State Police- Forensic Crime '
                                          'Lab',
 'Mastery Education': 'Mastery Education',
 'MathWorks': 'Mathzone',
 'Mathzone': 'Mathzone',
 'MattressCycle': 'MattressCycle',
 'Maxgen technologies Pvt. Ltd.': 'Maxgen technologies Pvt. Ltd.',
 "Mayor's Office": "Mayor's Office",
 'McKinney Automotive': 'McKinsey & Company',
 'McKinsey & Company': 'McKinsey & Company',
 'McNelis Investigative Services': 'McNelis Investigative Services',
 'Meaningful Day Services': 'Meaningful Day Services',
 'Mediabend Capital': 'Mediabend Capital',
 'Medical Solutions': 'Medical Solutions',
 'Medical University of South Carolina': 'Medical University of South Carolina',
 'Mercer University Athletics': 'Mercer University Athletics',
 'Meta': 'Meta',
 'Mia AI': 'Mia AI',
 'Michelin': 'Michelin',
 'Michigan Department of Licensing and Regulatory Affairs': 'Michigan '
                                                            'Department of '
                                                            'Licensing and '
                                                            'Regulatory '
                                                            'Affairs',
 'Michigan State University': 'NCAA',
 'Michigan State University College of Law': 'Michigan State University '
                                             'Extension',
 'Michigan State University Extension': 'Michigan State University Extension',
 'Microsoft': 'Microsoft',
 'Military Psychology (Journal)': 'Military Psychology (Journal)',
 'Mill Community Ministries': 'Mill Community Ministries',
 'Minas Cleaning': 'Minas Cleaning',
 'MindPalace': 'MindPalace',
 'Ministry Of Human Rights': 'Ministry Of Human Rights',
 'Minnesota Workwear': 'Minnesota Workwear',
 'Minviro': 'Minviro',
 'Monday Night Pictures': 'Monday Night Pictures',
 'Montage Technology, Inc': 'Montage Technology, Inc',
 'Morningstar': 'Morningstar',
 'Mui Ho Center for Cities': 'Mui Ho Center for Cities',
 'NASA': 'NASA',
 'NAVWAR': 'NAVWAR',
 'NBCUniversal': 'NBCUniversal',
 'NC Budo': 'NC Budo',
 'NCAA': 'NCAA',
 'NORC at the University of Chicago': 'University of Colorado Boulder',
 'Nancy Mace for Congress': 'Nancy Mace for Congress',
 'Nasa South Carolina Space Grant Consortium': 'NASA',
 'Nation Ford High School': 'Daniel High School',
 'National Brick Research Center': 'National Brick Research Center',
 'National Child Protection Task Force ': 'National Child Protection Task '
                                          'Force ',
 'National Science Foundation ': 'National Science Foundation ',
 'Naval Air Warfare Center Training Systems Division': 'US Navy',
 'Naval Special Warfare Group TEN ': 'US Navy',
 'Naveen Jindal School of Management, UT Dallas': 'Rady School of Management',
 'Nebraska Families Collaborative': 'Nebraska Families Collaborative',
 'Nephron Pharmaceuticals': 'Nephron Pharmaceuticals',
 'Nestle  Bhd.': 'Nestle  Bhd.',
 'Netspring - Internet Services & Consulting': 'Netspring - Internet Services '
                                               '& Consulting',
 'New England Claim Association': 'New England Claim Association',
 'New Hope Treatment Centers': 'New Hope Treatment Centers',
 'New York Air National Guard': 'New York Air National Guard',
 'New York City Housing Authority ': 'New York City Housing Authority ',
 'NextGen Venture Partners': 'Visionary Ventures',
 'Nice Hi-tech Centre': 'Nice Hi-tech Centre',
 'Nike Clemson Buff Grubb Lacrosse Camp': 'Nike Clemson Buff Grubb Lacrosse '
                                          'Camp',
 "Noah's Pest Control": "Noah's Pest Control",
 'North Carolina State University': 'Kenyon College',
 'North Central High School': 'Daniel High School',
 'North Gate Labs, LLC : WebSalesTool': 'North Gate Labs, LLC : WebSalesTool',
 'Northern Illinois University Athletics': 'Mercer University Athletics',
 'Notionworks Advisory, LLC': 'Capabilities LLC',
 'Nova Credit': 'NovaTech',
 'NovaTech': 'NovaTech',
 'Numerious Inc.': 'Numerious Inc.',
 'OCTL the Band': 'OCTL the Band',
 'OLYMPIA GYMNASTICS': 'OLYMPIA GYMNASTICS',
 'ORCHARD LAKE COUNTRY CLUB': 'The Old Club',
 'Oconee Federal Savings and Loan': 'Oconee Federal Savings and Loan',
 'Odyssey Hospice': 'Odyssey Hospice',
 'Ohio State University Comprehensive Cancer Center-James Cancer Hospital & Solove Research Institute': 'Ohio '
                                                                                                        'State '
                                                                                                        'University '
                                                                                                        'Comprehensive '
                                                                                                        'Cancer '
                                                                                                        'Center-James '
                                                                                                        'Cancer '
                                                                                                        'Hospital '
                                                                                                        '& '
                                                                                                        'Solove '
                                                                                                        'Research '
                                                                                                        'Institute',
 'Olive Garden': 'Olive Garden',
 'One Source The Background Check Company': 'One Source The Background Check '
                                            'Company',
 'Ontario Ministry of Economic Development, Job Creation and Trade': 'Ontario '
                                                                     'Ministry '
                                                                     'of '
                                                                     'Economic '
                                                                     'Development, '
                                                                     'Job '
                                                                     'Creation '
                                                                     'and '
                                                                     'Trade',
 'OpenBCI': 'OpenBCI',
 'Openfields': 'Openfields',
 'Oregon State Police': 'COPS',
 'Outset': 'Outset',
 'Oxenham Group': 'Oxenham Group',
 "P.F. Chang's": "P.F. Chang's",
 'PAE': 'PAE',
 'PATH Volleyball Academy LLC.': 'Volley One Volleyball Club',
 'PDRI': 'PDRI',
 'PIVOTAL INJURY AND REHAB INC': 'EXCEL REHAB & SPORTS',
 'PRIMA DUE DILIGENCE CONSULT': 'PRIMA DUE DILIGENCE CONSULT',
 'PRS Analytics LLC': 'Capabilities LLC',
 'PUGET CONSUMERS CO-OP': 'PUGET CONSUMERS CO-OP',
 'Pacific Northwest National Laboratory': 'Pacific Northwest National '
                                          'Laboratory',
 'Panera Bread': 'Panera Bread',
 'Pangea3': 'Pangea3',
 'Paramount': 'Paramount',
 'Parsons School of Design - The New School': 'Parsons School of Design - The '
                                              'New School',
 'Pathrise Talent': 'Pathrise Talent',
 "Payne's Window Cleaning LLC": "Payne's Window Cleaning LLC",
 'Pearce Center for Professional Communication': 'Pearce Center for '
                                                 'Professional Communication',
 'Pearson': 'Pearson',
 'Pearson Air Museum': 'Pearson Air Museum',
 'Pennsylvania Emergency Management Agency': 'Pennsylvania Emergency '
                                             'Management Agency',
 'Penske Truck Leasing': 'Penske Truck Leasing',
 'PeopleStrong': 'PeopleStrong',
 'PepTv3': 'PepTv3',
 'PetSmart': 'PetSmart',
 'PhotoFax': 'PhotoFax',
 'Physician Assistant Program at Ohio University': 'Physician Assistant '
                                                   'Program at Ohio University',
 'Pi Kappa Alpha International Fraternity': 'Delta Delta Delta Sorority',
 'Pickens County YMCA': 'Ymca - Deland',
 'Plastic Omnium': 'Plastic Omnium',
 'Platinum Protection & Investigations, LLC': 'Platinum Protection & '
                                              'Investigations, LLC',
 'Plymouth Rock Assurance Corp.': 'StoneX Group Inc.',
 'Podium': 'Podium',
 'Point Me to the Water': 'Point Me to the Water',
 'Ponder Diversity Group, LLC': 'Ponder Diversity Group, LLC',
 'Portland Private Investigators': 'Upstate Private Investigators',
 'Poth High School': 'Kenyon College',
 'Preparing the Future Workforce for the Era of Automated Vehicles (Weave)': 'Preparing '
                                                                             'the '
                                                                             'Future '
                                                                             'Workforce '
                                                                             'for '
                                                                             'the '
                                                                             'Era '
                                                                             'of '
                                                                             'Automated '
                                                                             'Vehicles '
                                                                             '(Weave)',
 'Preparing the Future\u202fWorkforce for the\u202fEra of\u202fAutomated\u202fVehicles (WEAVE)': 'Preparing '
                                                                                                 'the '
                                                                                                 'Future '
                                                                                                 'Workforce '
                                                                                                 'for '
                                                                                                 'the '
                                                                                                 'Era '
                                                                                                 'of '
                                                                                                 'Automated '
                                                                                                 'Vehicles '
                                                                                                 '(Weave)',
 'Primrose Schools': 'Primrose Schools',
 'Principal Financial Group': 'Principal Financial Group',
 'Prisma Health': 'UVA Health',
 'Procter & Gamble Hygiene & Health Care': 'Procter & Gamble Hygiene & Health '
                                           'Care',
 'Prodify': 'Prodify',
 'Professional Testing': 'Professional Testing',
 'Progressive Policy Institute': 'Progressive Policy Institute',
 'Project Crohn’s': 'Project Crohn’s',
 'Proterra': 'Proterra',
 'Protiviti': 'Proterra',
 'Proximum Labs': 'Proximum Labs',
 'Ptown Bikes': 'Ptown Bikes',
 'Public Relations Student Society of America ': 'Public Relations Student '
                                                 'Society of America ',
 'Publix Super Markets': 'Publix Super Markets',
 'Punto Central Luzon': 'Punto Central Luzon',
 'Purdue University': 'Lafayette College',
 'Q1 Productions': 'Q1 Productions',
 'Qnary': 'Qnary',
 'Quest Site Solutions': 'Quest Site Solutions',
 'Quince': 'Quince',
 'RHR International': 'RHR International',
 'RSK Assessment': 'RSK Assessment',
 'RTO National': 'RTO National',
 'Radancy': 'Radancy',
 'Radian': 'Radian',
 'Radiance': 'Radian',
 'RadioShack': 'RadioShack',
 'Rady School of Management': 'Rady School of Management',
 'Raleigh Country Club': 'The Old Club',
 'Ramah Day Camp in Nyack': 'Ramah Day Camp in Nyack',
 'Ramapo College of New Jersey': 'Valdosta State University',
 'Raytheon': 'Raytheon',
 'Recology': 'Recology',
 'RedFile Technologies, Inc.': 'RedFile Technologies, Inc.',
 'Refresh Miami': 'Refresh Miami',
 'Renaissance Strategy Worldwide': 'Renaissance Strategy Worldwide',
 'Renewable Water Resources ': 'Renewable Water Resources ',
 'Research Administration Capacity Heightening in South Carolina (REACH-SC)': 'Research '
                                                                              'Administration '
                                                                              'Capacity '
                                                                              'Heightening '
                                                                              'in '
                                                                              'South '
                                                                              'Carolina '
                                                                              '(REACH-SC)',
 'Resources Global Professionals': 'Resources Global Professionals',
 'Resurgens Orthopaedics': 'Resurgens Orthopaedics',
 'Resurgent Capital Services': 'Resurgent Capital Services',
 'Rick Erwin Dining Group': 'Rick Erwin Dining Group',
 'Ringgold Telephone Company ': 'Ringgold Telephone Company ',
 'Rishabh Software': 'Rishabh Software',
 'River Garden Senior Services': 'River Garden Senior Services',
 'Riverfront Family YMCA': 'Ymca - Deland',
 'Robert H. Brooks Sports Science Institute': 'NCAA',
 'Rock Security Command Center': 'Rock Security Command Center',
 'Rogers Group Inc.': 'Carters Inc.',
 'Rover.com': 'Rover.com',
 'Rush Capital Consulting & Co': 'Rush Capital Consulting & Co',
 'SC Statehouse': 'SC Statehouse',
 'SCA Health': 'SCA Health',
 'SENT Ventures': 'VentureSouth',
 'SKI Investigations, Inc.': 'SKI Investigations, Inc.',
 'SMI Aware': 'SMI Aware',
 'SMU Mustangs': 'SMU Mustangs',
 'SNI Technology': 'SNI Technology',
 'SPCA Serving Erie County, NY | Lipsey Veterinary Clinic | 300 Harlem Rd. | West Seneca, NY 14224|': 'Wyoming '
                                                                                                      'County '
                                                                                                      'SPCA',
 'SR Max Slip Resistant Shoes': 'SR Max Slip Resistant Shoes',
 'SRM Economics': 'SRM Economics',
 'STARK RFID': 'STARK RFID',
 'SUMMIT Engineering, Laboratory & Testing, Inc.': 'Pacific Northwest National '
                                                   'Laboratory',
 'Safehome Fencing': 'Safehome Fencing',
 'Saint Elizabeth Ann Seton Catholic School': 'Saint Elizabeth Ann Seton '
                                              'Catholic School',
 'Sairaj Telecom': 'Sairaj Telecom',
 'Sam Houston State University': 'Sam Houston State University',
 'Sama': 'Sama',
 "Samson's Mullet": "Samson's Mullet",
 'San Antonio Texas Area': 'San Antonio Texas Area',
 'Sanfoundry': 'Sanfoundry',
 'Satellite Investigations': 'Satellite Investigations',
 'SavSides Designs': 'SavSides Designs',
 'ScanSource': 'ScanSource',
 'Schneider Contracting LLC': 'Schneider Contracting LLC',
 'Scoot Education': 'Scoot Education',
 'ScopeStack - Services CPQ': 'ScopeStack - Services CPQ',
 'Seacoast Church Columbia': 'Seacoast Church Columbia',
 'Second Shift Chicago': 'Chicago Inno',
 'Seed2C': 'Seed2C',
 'Self-employed': 'Self-employed',
 'Sema4': 'Sema4',
 'Seneca Group': 'Seneca Group',
 'Shardeum': 'Shardeum',
 'Sheppard Mullin Richter & Hampton LLP': 'Sheppard Mullin Richter & Hampton '
                                          'LLP',
 'Shining Stars': 'Shining Stars',
 'Sidewall Pizza Company': 'Sidewall Pizza Company',
 'Silver Fern': 'Silver Fern',
 'Silverback Enterprise Group': 'Silverback Enterprise Group',
 'Sleep Number': 'Sleep Number',
 'Smith & Carson': 'Smith & Carson',
 'Snappy express wash': 'Snappy express wash',
 'SnowcatCloud Inc.': 'Cloud Court, Inc.',
 'Sober Roots': 'Sober Roots',
 'Social Slooth': 'Hinge Social',
 'Software AG': 'Software AG',
 'Solero': 'Solero',
 'Solutionz Group, LLC': 'Carters Inc.',
 'Sound Solar Systems': 'Sound Solar Systems',
 'South Carolina Army National Guard': 'New York Air National Guard',
 'South Carolina Ffa Association': 'South Carolina Ffa Center',
 'South Carolina Ffa Center': 'South Carolina Ffa Center',
 'South Carolina Republican Party': 'Carolina Girls',
 'South Riding Dance Academy': 'South Riding Dance Academy',
 'Southern Crown Partners': 'Southern Crown Partners',
 'Southern First Bank': 'Main Street Banks',
 'Southern Illinois University, Carbondale': 'University of Colorado Boulder',
 'Southern Magnolia Living': 'Southern Magnolia Living',
 'Southern Wesleyan University': 'ALIVE Wesleyan Church',
 'SouthernCarlson': 'SouthernCarlson',
 'Southview Community Church': 'Grace Church ',
 'Southwest Iowa Family Access Center, LLC': 'Southwest Iowa Family Access '
                                             'Center, LLC',
 'Spero Financial': 'Spero Financial',
 'Spiegel Sohmer Inc.': 'Spiegel Sohmer Inc.',
 'St. Francis Foundation - Bon Secours Health System': 'Bon Secours Health '
                                                       'System Ireland',
 'St. Michael the Archangel High School of Baton Rouge': 'St. Michael the '
                                                         'Archangel High '
                                                         'School of Baton '
                                                         'Rouge',
 'Stagecraft Networks, LLC': 'Stagecraft Networks, LLC',
 'Starbucks': 'Subway',
 'State Farm': 'State Farm',
 'State of Iowa - Executive Branch': 'State of Iowa - Executive Branch',
 'Stealth Startup': 'Stealth Startup',
 'SteerBridge': 'SteerBridge',
 'Steinway & Sons': 'Steinway & Sons',
 'StepValue - Web Intelligence': 'StepValue - Web Intelligence',
 'StockTrim - Smart Inventory Forecasting Software': 'StockTrim - Smart '
                                                     'Inventory Forecasting '
                                                     'Software',
 'StoneX Group Inc.': 'StoneX Group Inc.',
 'Storitz': 'Storitz',
 'Strategic Insight Group (SIG)': 'Strategic Insight Group (SIG)',
 'StreetShares ': 'StreetShares ',
 'Stripe': 'Stripe',
 'Strive Sales': 'Strive Sales',
 'Strossner’s Bakery & Cafe': 'Strossner’s Bakery & Cafe',
 'Stryker Advisors': 'Stryker Sage',
 'Stryker Sage': 'Stryker Sage',
 'Student Basic Needs Coalition': 'Student Basic Needs Coalition',
 'Study Smart Tutors': 'Tutor.com',
 'Subway': 'Subway',
 'Sunny Days Entertainment, LLC': 'Sunny Days Entertainment, LLC',
 'Super Group': 'MTN Group',
 'Supernal AI': 'BigBear.ai',
 'Supply Chain Technologies LLC': 'Capabilities LLC',
 'Surv': 'Surv',
 'Susquehanna International Group, LLP (SIG)': 'Susquehanna International '
                                               'Group, LLP (SIG)',
 'Swampfox Technologies': 'Swampfox Technologies',
 "Swirlee's Frozen Yogurt": "Swirlee's Frozen Yogurt",
 'Sysco': 'Sysco',
 'TD': 'TD',
 'TEKsystems': 'TEKsystems',
 'THE CLIFFS AT MOUNTAIN PARK, LLC': 'THE CLIFFS AT MOUNTAIN PARK, LLC',
 'TIC - The Industrial Company': 'TIC - The Industrial Company',
 'TRACE Research Group': 'Trace Camp',
 'TRC Talent Solutions': 'Pathrise Talent',
 'Tagler': 'Tagler',
 'Talented Business Solutions Inc.': 'Talented Business Solutions Inc.',
 'Tampa Bay Buccaneers': 'Tampa Bay Buccaneers',
 'Tata Consultancy Services': 'Tata Consultancy Services',
 'Taylors First Baptist Church': 'Grace Church ',
 'Taylors Mill': 'Les Mills ',
 'Taylors Townsquare': 'Taylors Townsquare',
 'Teach and Learn with Georgia': 'Teach and Learn with Georgia',
 'Technanosoft Technologies': 'NovaTech',
 'Techstars London': 'NovaTech',
 'Techtronic Industries - TTI': 'Techtronic Industries - TTI',
 'Teneo': 'Teneo',
 'Terratory': 'Terratory',
 'Tesla': 'Tesla',
 'Texas Hunger Initiative': 'Texas Hunger Initiative',
 'The Bail Project': 'The Bail Project',
 'The Blood Connection': 'The Blood Connection',
 'The Cathay School': 'The Cathay School',
 'The Champions Center for Special Children': 'The Champions Center for '
                                              'Special Children',
 'The Citadel': 'The Citadel',
 'The Destek Networking Group': 'The Destek Networking Group',
 'The Erwin Center for Brand Communications': 'The Erwin Center for Brand '
                                              'Communications',
 'The Fox Hill Club': 'The Old Club',
 'The Free Website Guys': 'The Free Website Guys',
 'The Fulbright Program': 'The Fulbright Program',
 'The Galley': 'The Galley',
 'The Garvey Group': 'The Garvey Group',
 'The Great Library of Alexandria': 'The Great Library of Alexandria',
 'The House': 'Houses',
 'The Inn At Patrick Square': 'The Inn At Patrick Square',
 'The Intersect Group': 'overlap',
 'The Ivy Place': 'The Ivy Place',
 'The JDM Group': 'The JDM Group',
 'The Love Akron Network': 'NBCUniversal',
 'The Makers Collective': 'The Makers Collective',
 'The Market in the Square': 'The Market in the Square',
 'The Mason Jar Tavern': 'The Mason Jar Tavern',
 'The Old Club': 'The Old Club',
 'The Osinoff Group': 'The Osinoff Group',
 'The Pines at Davidson': 'The Pines at Davidson',
 'The Preiss Company': 'The Preiss Company',
 'The Rise Coffee Bar': 'The Rise Coffee Bar',
 'The Robison Group': 'The Osinoff Group',
 'The Rolling Tape': 'The Rolling Tape',
 'The Shepherd Hotel': 'The Shepherd Hotel',
 'The Shift Chicago': 'Chicago Inno',
 'The Sovereignty Foundation': 'Eternity Foundation',
 'The UPS Store 0089': 'UPS Ventures',
 'The University of Georgia': 'Georgia Pacific',
 'The University of Texas at Austin': 'Sam Houston State University',
 'The Walt Disney Company': 'Disneyland Resort',
 'Thomson Reuters': 'Thomson Reuters',
 'Ticketmaster': 'Ticketmaster',
 'Time Machine Capital² Limited': 'Time Machine Capital² Limited',
 'Tokensoft Transfer Agent': 'Tokensoft Transfer Agent',
 'Trace Camp': 'Trace Camp',
 'Trend Micro': 'Trend Micro',
 'Tri County Ace Hardware': 'Tri County Ace Hardware',
 'Tri-County Technical College': 'Tri-County Technical College',
 'Trilogy Investment Group': 'ClubCorp Holdings',
 'Triune Mercy Center': 'Triune Mercy Center',
 'Troutman Pepper': 'Troutman Pepper',
 'Troutman Pepper Locke LLP': 'Troutman Pepper',
 'True Value Company': 'True Value Company',
 'Truist': 'Truist',
 'Truveris': 'Truveris',
 'Turing': 'Turing',
 'Tutor.com': 'Tutor.com',
 'U.S. Department of State': 'U.S. Department of State',
 'U.S. Marine Corps': 'US Navy',
 'U.S. Office of Personnel Management ': 'U.S. Department of State',
 'U.S. Space & Rocket Center': 'NASA',
 'UCLA Journal of International Law and Foreign Affairs': 'Cambridge Review of '
                                                          'International '
                                                          'Affairs',
 'UGA Carl Vinson Institute of Government': 'UGA Carl Vinson Institute of '
                                            'Government',
 'UGA Leadership Education and Development (LEAD) Lab': 'UGA Leadership and '
                                                        'Performance Dynamics '
                                                        'Lab',
 'UGA Leadership and Performance Dynamics Lab': 'UGA Leadership and '
                                                'Performance Dynamics Lab',
 'UMBC': 'UMBC',
 'UPS Healthcare': 'UPS Ventures',
 'UPS Ventures': 'UPS Ventures',
 'US Air Force': 'US Navy',
 'US Army Reserve': 'US Army Reserve',
 'US Navy': 'US Navy',
 'USA Baseball': 'USA Baseball',
 'USC Schaeffer Center for Health Policy & Economics': 'USC Schaeffer Center '
                                                       'for Health Policy & '
                                                       'Economics',
 'USF Athletics': 'NCAA',
 'USHEALTH Advisors': 'USHEALTH Advisors',
 'UVA Biocomplexity Institute': 'UVA Health',
 'UVA Health': 'UVA Health',
 'Ubisoft': 'Ubisoft',
 'UniCourt': 'Unisys',
 'Unisys': 'Unisys',
 'United Airlines': 'United Airlines',
 'United States Air Force': 'US Navy',
 'United States Amateur Baseball League': 'USA Baseball',
 'United States Department of Defense': 'U.S. Department of State',
 'United States Marine Corps': 'US Navy',
 'United States Patent and Trademark Office ': 'United States Patent and '
                                               'Trademark Office ',
 'United States Probation Office- Western District of Texas': 'United States '
                                                              'Probation '
                                                              'Office- Western '
                                                              'District of '
                                                              'Texas',
 'United States Senate': 'United States Senate',
 'United States Senate Committee on the Budget': 'United States Senate',
 'United Way Of Kershaw County': 'United Way Of Kershaw County',
 'Unity': 'Unity',
 'Universal Protection Svc': 'Universal Protection Svc',
 'University Innovation Fellows': 'University Innovation Fellows',
 'University of Alabama at Birmingham': 'Sam Houston State University',
 'University of Calgary': 'Kansai University',
 'University of Central Florida': 'South Carolina Ffa Center',
 'University of Chicago': 'Kenyon College',
 'University of Colorado Boulder': 'University of Colorado Boulder',
 'University of Dayton': 'Kenyon College',
 'University of Dayton Biology Department': 'University of Dayton Biology '
                                            'Department',
 'University of Florida': 'NCAA',
 'University of Kentucky College of Public Health': 'University of Kentucky '
                                                    'College of Social Work',
 'University of Kentucky College of Social Work': 'University of Kentucky '
                                                  'College of Social Work',
 'University of North Carolina Wilmington': 'Medical University of South '
                                            'Carolina',
 'University of North Carolina at Chapel Hill': 'Medical University of South '
                                                'Carolina',
 'University of Oklahoma': 'Kenyon College',
 'University of Ottawa': 'Lafayette College',
 'University of Pennsylvania': 'Kenyon College',
 'University of South Carolina': 'South Carolina Ffa Center',
 'University of South Carolina Upstate': 'University of Colorado Boulder',
 'University of Tampa': 'UMBC',
 'University of Washington': 'Kenyon College',
 'University of Washington Human Centered Design & Engineering': 'Design for '
                                                                 'America',
 'University of Washington Information School': 'University of Colorado '
                                                'Boulder',
 'University of West Florida': 'NCAA',
 'Unlimited': 'Unlimited',
 'Upstate AHEC': 'AID Upstate',
 'Upstate Pool Management I': 'Upstate Pool Management I',
 'Upstate Pool Management Inc': 'Upstate Pool Management I',
 'Upstate Private Investigators': 'Upstate Private Investigators',
 'Upstate SC Alliance': 'AID Upstate',
 'UrbanStems': 'UrbanStems',
 'Utah Warriors Rugby': 'Byu Rugby',
 'VCU Recreational Sports': 'VCU Recreational Sports',
 'Valdosta State University': 'Valdosta State University',
 'Vanderbilt University Medical Center': 'Lexington Medical Center',
 'Various': 'Various',
 'Various Corporate and Public Sector Clients': 'Various Corporate and Public '
                                                'Sector Clients',
 'VastoFi': 'VastoFi',
 'Vazkor Technologies': 'Vazkor Technologies',
 'Velti': 'Velti',
 'Venable LLP': 'Venable LLP',
 'Venture Measurement Company': 'VentureSouth',
 'VentureSouth': 'VentureSouth',
 'Vertocity': 'Vertocity',
 'Vesca Robotics': 'Vesca Robotics',
 'Vibranium Labs': 'Vibranium Labs',
 'Virginia Tech': 'NovaTech',
 'Visa': 'Visa',
 'Visionary Ventures': 'Visionary Ventures',
 'Volley One Volleyball Club': 'Volley One Volleyball Club',
 'Volunteers of America Western Washington': 'Volunteers of America Western '
                                             'Washington',
 'W. Lee Flowers & Co': 'W. Lee Flowers & Co',
 'WARECAP': 'WARECAP',
 'WAREHAM GATEMEN BASEBALL INC': 'WAREHAM GATEMEN BASEBALL INC',
 'WEAVE NSF': 'WEAVE NSF',
 'WYCKOFF REFORMED CHURCH CEMETERY': 'WYCKOFF REFORMED CHURCH CEMETERY',
 'Walden Consulting': 'Walden Consulting',
 'Walgreens': 'Walgreens',
 'Walmart': 'Amazon',
 'Walt Disney World': 'Disneyland Resort',
 'Walter P Moore': 'Walter P Moore',
 'Walter Reed Army Institute of Research': 'Walter Reed Army Institute of '
                                           'Research',
 'Wampum': 'Wampum',
 'Warner Bros. Discovery': 'Warner Bros. Discovery',
 'WatchFit': 'WatchFit',
 'Waves Express Car Wash': 'Waves Express Car Wash',
 'Wayfair': 'Wayfair',
 'Waynewood Kennels': 'Waynewood Kennels',
 'Wears Valley Ranch': 'Wears Valley Ranch',
 'Weber Shandwick Asia': 'Weber Shandwick Asia',
 'Webs': 'Webs',
 'WebsterRogers LLP': 'WebsterRogers LLP',
 'Webutation, Inc': 'Webutation, Inc',
 'Weil, Gotshal & Manges LLP': 'Weil, Gotshal & Manges LLP',
 'Wells Fargo': 'Wells Fargo',
 "Wendy's Dance Company": "Wendy's Dance Company",
 'Westchester Summer Day': 'Westchester Summer Day',
 'Westfield Police Department': 'Westfield Police Department',
 "Whit's Frozen Custard": "Whit's Frozen Custard",
 'White Elm Group, LLC': 'White Elm Group, LLC',
 'Whitesville Elementary School': 'Daniel High School',
 'Wilbur O. and Ann Powers College of Business at Clemson University': 'Wilbur '
                                                                       'O. and '
                                                                       'Ann '
                                                                       'Powers '
                                                                       'College '
                                                                       'of '
                                                                       'Business '
                                                                       'at '
                                                                       'Clemson '
                                                                       'University',
 'Willow Bridge Property Company': 'Willow Bridge Property Company',
 'WinShape Camps': 'WinShape Camps',
 'Wipro': 'Wipro',
 'Wireless Lifestyle': 'Wireless Lifestyle',
 'Wise Agents': 'Wise Agents',
 'Wordsearch Bible': 'Wordsearch Bible',
 'Workr Beeing': 'Workr Beeing',
 'World Vision Kenya': 'World Vision Kenya',
 'Worth Search': 'Worth Search',
 'Wunderlich Securities': 'Wunderlich Securities',
 'Wyoming County SPCA': 'Wyoming County SPCA',
 'XG Consultants Group': 'XG Consultants Group',
 'YMCA of the USA': 'Ymca - Deland',
 'Ymca - Deland': 'Ymca - Deland',
 'YoReparo.com': 'YoReparo.com',
 'YouCaring': 'YouCaring',
 'Young Life': 'Young Life',
 'Young Office': 'Young Office',
 'ZELITE': 'Zerf',
 'ZERO Connect': 'ZERO Connect',
 'Zerf': 'Zerf',
 'Zero Hiring': 'Zero Hiring',
 'Zips Car Wash LLC': 'Zips Car Wash LLC',
 'Zoo': 'Zoo',
 'blue moon realty, llc': 'Beeby, Inc.',
 'cis': 'cis',
 'clemson university social media listening center': 'Clemson University '
                                                     'Social Media Listening '
                                                     'Center',
 'eGage Human Capital Consulting': 'eGage Human Capital Consulting',
 'escala': 'escala',
 'gap intelligence': 'gap intelligence',
 'gategroup': 'gategroup',
 'hattricks': 'hattricks',
 'interstate reporting co., inc.': 'Corporate Resolutions Inc.',
 'joint special operations command': 'joint special operations command',
 'konaAI': 'konaAI',
 'lightning': 'lightning',
 'mGage': 'mGage',
 'melt.': 'melt.',
 'naval air warfare center aircraft division ': 'US Navy',
 'overlap': 'overlap',
 'panya computech': 'panya computech',
 'retickr': 'retickr',
 "samaritan's purse international relief": "samaritan's purse international "
                                           'relief',
 'self': 'self',
 'talabat': 'talabat',
 'tap.': 'tap.',
 'the church at lifepark': 'Grace Church ',
 'university physical therapy and sports medicine': 'MX Physical Therapy'}
